/**
 * Build script (run with `bun run build`).
 *
 *  1. Generates dist/theme.css from the palette + token mapping. The CSS
 *     mirrors GitHub's own light/dark/auto resolution so the right Everforest
 *     variant is active with zero flash, and is gated on html:not([data-ef=off])
 *     so the popup can toggle it. Contrast variants emit only the tokens that
 *     differ from "medium" to keep the file lean.
 *  2. Bundles src/content.ts and popup/popup.ts to dist/*.js via Bun.
 *  3. Copies manifest.json, the popup HTML/CSS and icons into dist/.
 */

import { mkdir, rm, cp, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { resolve, type Contrast, type Mode } from "./palette";
import { buildTokens } from "./mapping";

const ROOT = path.resolve(import.meta.dir, "..");
const DIST = path.join(ROOT, "dist");

// Enabled when not explicitly turned off. "Sync" (follow GitHub's own
// data-color-mode) is the *implicit* default — it matches when the user hasn't
// forced a mode, so the theme applies with zero flash before the content
// script runs. Forcing light/dark sets data-ef-mode.
const ON = 'html:not([data-ef="off"])';
const SYNC = ':not([data-ef-mode="light"]):not([data-ef-mode="dark"])';
const withContrast = (sel: string, contrast: string): string =>
  contrast ? `${sel}[data-ef-contrast="${contrast}"]` : sel;

const syncLight = (c: string) => withContrast(`${ON}${SYNC}[data-color-mode="light"]`, c);
const syncAuto = (c: string) => withContrast(`${ON}${SYNC}[data-color-mode="auto"]`, c);
const syncDark = (c: string) => withContrast(`${ON}${SYNC}[data-color-mode="dark"]`, c);
const forceLight = (c: string) => withContrast(`${ON}[data-ef-mode="light"]`, c);
const forceDark = (c: string) => withContrast(`${ON}[data-ef-mode="dark"]`, c);

function declBlock(
  selectors: string[],
  tokens: Record<string, string>,
  extra: Record<string, string> = {},
): string {
  const lines = [
    ...Object.entries(extra).map(([k, v]) => `  ${k}: ${v} !important;`),
    ...Object.entries(tokens).map(([k, v]) => `  ${k}: ${v} !important;`),
  ];
  return `${selectors.join(",\n")} {\n${lines.join("\n")}\n}\n`;
}

function diff(full: Record<string, string>, base: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const k in full) if (full[k] !== base[k]) out[k] = full[k]!;
  return out;
}

function generateCss(): string {
  const contrasts: Contrast[] = ["hard", "soft"];
  const lightMed = buildTokens(resolve("light", "medium"));
  const darkMed = buildTokens(resolve("dark", "medium"));
  const lightDiff = (c: Contrast) => diff(buildTokens(resolve("light", c)), lightMed);
  const darkDiff = (c: Contrast) => diff(buildTokens(resolve("dark", c)), darkMed);

  const parts: string[] = [
    "/* Everforest for GitHub — GENERATED by src/build.ts. Do not edit by hand. */",
    "/* Palette: github.com/sainnhe/everforest */",
    "",
  ];

  // ── LIGHT — sync(light|auto) + forced light ──
  parts.push(declBlock([syncLight(""), syncAuto(""), forceLight("")], lightMed, { "color-scheme": "light" }));
  for (const c of contrasts) {
    parts.push(declBlock([syncLight(c), syncAuto(c), forceLight(c)], lightDiff(c)));
  }

  // ── DARK — sync(dark) + forced dark ──
  parts.push(declBlock([syncDark(""), forceDark("")], darkMed, { "color-scheme": "dark" }));
  for (const c of contrasts) {
    parts.push(declBlock([syncDark(c), forceDark(c)], darkDiff(c)));
  }

  // ── DARK via sync + auto + OS dark (overrides the light-from-auto block) ──
  const media: string[] = [
    declBlock([syncAuto("")], darkMed, { "color-scheme": "dark" }),
    ...contrasts.map((c) => declBlock([syncAuto(c)], darkDiff(c))),
  ];
  parts.push(`@media (prefers-color-scheme: dark) {\n${media.join("")}}\n`);

  return parts.join("\n");
}

// ── Companion Chrome *browser* themes ─────────────────────────────────────
// A Chrome theme can't live in the same package as a content-script extension,
// so we emit standalone theme packages (loaded separately) from the same
// palette, keeping the browser UI and the github.com restyle in lockstep.
function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
}

function chromeThemeManifest(mode: Mode): unknown {
  const p = resolve(mode, "medium");
  return {
    manifest_version: 3,
    name: `Everforest ${mode === "dark" ? "Dark" : "Light"}`,
    version: "1.0.0",
    description:
      `A warm, low-contrast Everforest theme for the Chrome browser UI — ` +
      `companion to "Everforest for GitHub".`,
    icons: { "128": "icon-128.png" },
    theme: {
      colors: {
        frame: hexToRgb(p.bg_dim),
        frame_inactive: hexToRgb(p.bg_dim),
        toolbar: hexToRgb(p.bg0),
        tab_text: hexToRgb(p.fg),
        tab_background_text: hexToRgb(p.grey1),
        bookmark_text: hexToRgb(p.fg),
        toolbar_text: hexToRgb(p.fg),
        omnibox_background: hexToRgb(p.bg1),
        omnibox_text: hexToRgb(p.fg),
        ntp_background: hexToRgb(p.bg0),
        ntp_text: hexToRgb(p.fg),
        ntp_link: hexToRgb(p.blue),
        button_background: hexToRgb(p.bg0),
      },
      // Tint toolbar button icons toward light (dark theme) / dark (light theme).
      tints: { buttons: mode === "dark" ? [-1, -1, 0.8] : [-1, -1, 0.25] },
      properties: { ntp_logo_alternate: mode === "dark" ? 1 : 0 },
    },
  };
}

async function buildChromeThemes(): Promise<void> {
  for (const mode of ["dark", "light"] as Mode[]) {
    const dir = path.join(ROOT, "chrome-themes", `everforest-${mode}`);
    await mkdir(dir, { recursive: true });
    await writeFile(
      path.join(dir, "manifest.json"),
      JSON.stringify(chromeThemeManifest(mode), null, 2) + "\n",
    );
    if (existsSync(path.join(ROOT, "icons/icon-128.png"))) {
      await cp(path.join(ROOT, "icons/icon-128.png"), path.join(dir, "icon-128.png"));
    }
  }
}

async function build(): Promise<void> {
  const t0 = performance.now();
  await rm(DIST, { recursive: true, force: true });
  await mkdir(DIST, { recursive: true });

  // 1. theme.css
  await writeFile(path.join(DIST, "theme.css"), generateCss(), "utf8");

  // 2. bundle scripts
  const result = await Bun.build({
    entrypoints: [path.join(ROOT, "src/content.ts"), path.join(ROOT, "popup/popup.ts")],
    outdir: DIST,
    target: "browser",
    minify: true,
    naming: "[name].js",
  });
  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error("Bun.build failed");
  }

  // 3. static assets
  await cp(path.join(ROOT, "manifest.json"), path.join(DIST, "manifest.json"));
  await cp(path.join(ROOT, "popup/popup.html"), path.join(DIST, "popup.html"));
  await cp(path.join(ROOT, "popup/popup.css"), path.join(DIST, "popup.css"));
  await cp(path.join(ROOT, "src/google.css"), path.join(DIST, "google.css"));
  await cp(path.join(ROOT, "src/x.css"), path.join(DIST, "x.css"));
  if (existsSync(path.join(ROOT, "icons"))) {
    await cp(path.join(ROOT, "icons"), path.join(DIST, "icons"), {
      recursive: true,
      filter: (src) => !src.endsWith(".py"), // ship the PNGs, not the generator
    });
  }

  // 4. companion browser themes
  await buildChromeThemes();

  const ms = (performance.now() - t0).toFixed(0);
  console.log(`✓ built dist/ + chrome-themes/ in ${ms}ms`);
}

await build();

if (process.argv.includes("--watch")) {
  const { watch } = await import("node:fs");
  console.log("… watching src/ and popup/ for changes (Ctrl-C to stop)");
  let timer: ReturnType<typeof setTimeout> | null = null;
  const schedule = () => {
    if (timer) clearTimeout(timer);
    timer = setTimeout(() => build().catch((e) => console.error(e)), 120);
  };
  for (const dir of ["src", "popup"]) {
    watch(path.join(ROOT, dir), { recursive: true }, schedule);
  }
  watch(path.join(ROOT, "manifest.json"), schedule);
}
